name: 'Wait'
description: 'Wait a designated number of milliseconds'
inputs:
  folder: # id of input
    description: 'the key of the folder to make a deploy'
    required: true
  domain: # id of input
    description: 'the domain on sbx to make a deploy'
    required: true
  username: # id of input
    description: 'the username to make deploy'
    required: true
  password: # id of input
    description: 'the password'
    required: true
  attempts: # id of input
    description: '# attempts for deploy'
    required: true
  path: # id of input
    description: 'Folder path to make deploy'
    required: true
outputs:
  time: # output will be available to future steps
    description: 'The message to output'
runs:
  using: 'node12'
  main: 'dist/index.js'
